version: '3'
services:
  web:
    build: ./
    command: >
      sh -c "./wait-for-postgres.sh postgres npm run start && npm run migrate"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASS: root
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: my_db
      HTTP_PORT: 8070
    ports:
      - '8070:8070'
  postgres:
    restart: always
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules